# declare a service

apiVersion: v1
kind: Service
metadata:
  name: petclinic-svc
  labels:
    app: petclinic

# define and configure service to access port 8080
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30500
    protocol: TCP
  selector:
    app: petclinic

