# declare a service object
apiVersion: v1
kind: Service
metadata:
  name: petclinic-svc
  labels:
    app: petclinic
    version: v1.1
    env: prod
# define and configure service to acces 8080 port
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32501
    protocol: TCP
  selector:
    app: petclinic
